### ISSUE TITLE
wrong type and value while converting from xml to json

### ISSUE THREAD

**Issue by lucarocchi** [smart-fun/XmlToJson#2] opened 2017-04-02 19:26 UTC
hello , here is the problem : 
1) my xml contains an attribute id="12345.320" 
2) as i converted it to json and get the id back as string, it became "12345.32", that is the trailing 0 disappear

What's happened?
The problems comes from the code below , 
in fact the id get converted as Double,and that was not supposed to be the case 
So,my opinion  it would be better to simply set the value as string and let is as is
Just want to notice you about that in the case you would fix it 

Thank you for your good work
Luca

private void putContent(JSONObject json, String tag, String content) 
....
                    try {
                        Integer integer = Integer.parseInt(content);
                        json.put(tag, integer);
                    } catch (NumberFormatException exceptionInt) {
                        try {
                            Double number = Double.parseDouble(content);
                            json.put(tag, number.doubleValue());
                        } catch (NumberFormatException exceptionDouble) {
                            json.put(tag, content);
                        }
                    }

**Comment by smart-fun** [comment] 2017-04-02 19:51
Hello Luca and thank you for your feedback.

It sounds logical to me that string numbers are converted to numbers, but I understand your need.
I can propose to add some options like "force an attribute to be a String" or "force a content to be a String".
With that kind of options the user will be able to choose between String or Double.

What do you think ?

Arnaud.

**Comment by lucarocchi** [comment] 2017-04-02 20:41
I think  that would be a good solution as well !
Luca

**Comment by smart-fun** [comment] 2017-04-03 08:14
Hello Luca,

I have added a method in the Builder: forceStringForPath(String path). It works for both Attributes or Content. It can be used like this:

```java
String json = new XmlToJson.Builder(xml)
        .forceStringForPath("/library/book/id")
        .build().toString();
```

I did a pre-release 1.2.1, could you please use it and tell me if all is ok for you, so that I can officially release it?

thanks!

Arnaud.

**Comment by lucarocchi** [comment] 2017-04-03 09:38
Yes it works as expected, thank you
Luca
<img width="799" alt="screen shot 2017-04-03 at 11 36 52" src="https://cloud.githubusercontent.com/assets/213265/24603646/f12153a0-1861-11e7-98ec-c20b610cb667.png">

**Comment by smart-fun** [comment] 2017-04-03 11:51
Good news ! :)

I just released this new version and updated the documentation.

Thanks again for your feedback!

I'm now closing this ticket as the problem is solved.

Arnaud.

**Closed by smart-fun** 2017-04-03 11:51 UTC
